# Generated by Django 2.1.5 on 2019-01-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('article_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('article_title', models.CharField(max_length=512)),
                ('article_date', models.DateField()),
                ('article_cover', models.CharField(max_length=4096)),
                ('article_content', models.TextField()),
            ],
        ),
    ]
