# Generated by Django 2.1.5 on 2019-01-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.CharField(max_length=255)),
                ('article_title', models.CharField(max_length=512)),
                ('article_date', models.DateField()),
                ('article_cover', models.CharField(max_length=4096)),
                ('article_content', models.TextField()),
            ],
        ),
    ]
