# Generated by Django 2.1.7 on 2019-02-26 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('article_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('article_title', models.CharField(max_length=512)),
                ('article_date', models.DateField()),
                ('article_cover', models.CharField(max_length=4096)),
                ('article_source', models.CharField(max_length=255)),
                ('article_content', models.TextField()),
                ('article_editor', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=255, unique=True)),
                ('category_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='article_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='api.category', to_field='category_id'),
        ),
    ]
